on:
  workflow_dispatch:
  schedule:
    - cron: '40 16 * * *'
    - cron: '40 5  * * *' 
    - cron: '40 4  * * *'

jobs:
  call-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call cron endpoint
        shell: bash
        env: 
          CRONJOB_SECRET: ${{ secrets.CRONJOB_SECRET }}
        run: |
          curl --header "X-CronSecret: $CRONJOB_SECRET" -X GET https://tday.ohmz.cloud/api/cron/rescheduleTodo
  
